[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  GENERATE_SOURCEMAP = "false"

# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
