name: Clear Netlify Cache
on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Clear Netlify cache
        run: netlify build:clear-cache --site ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
